version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Download and unzip the Scanner
          command: |
            export SONAR_SCANNER_VERSION=3.3.0.1492
            export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION
            rm -rf $SONAR_SCANNER_HOME
            mkdir -p $SONAR_SCANNER_HOME
            curl -sSLo $HOME/.sonar/sonar-scanner.zip http://repo1.maven.org/maven2/org/sonarsource/scanner/cli/sonar-scanner-cli/$SONAR_SCANNER_VERSION/sonar-scanner-cli-$SONAR_SCANNER_VERSION.zip
            unzip $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
            rm $HOME/.sonar/sonar-scanner.zip
            export PATH=$SONAR_SCANNER_HOME/bin:$PATH
            export SONAR_SCANNER_OPTS="-server"

            curl -LsS https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip > build-wrapper-linux-x86.zip
            unzip build-wrapper-linux-x86.zip
      - run:
          name: Execute the Scanner
          command: |
            build-wrapper-linux-x86-64 --out-dir bw-output make clean all
            sonar-scanner \
              -Dsonar.projectKey=TomohiroHayashi_ordinals \
              -Dsonar.organization=tomohirohayashi \
              -Dsonar.sources=. \
              -Dsonar.cfamily.build-wrapper-output=bw-output \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=0f53837dc3307d7e10704647af18d7d4f37b30e0
